# Check out https://docs.codemagic.io/yaml/yaml-getting-started/ for more information.
# Please review and update values in curly braces

workflows:
  default-workflow:           # workflow ID
    name: Default Workflow    # workflow name displayed in Codemagic UI
    max_build_duration: 60    # build duration in minutes (min 1, max 120)
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Analyze Flutter 
        script: |
          flutter analyze

      - name: Build iOS Simulator
        script: |
          flutter build ios --debug --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
