# Check out https://docs.codemagic.io/yaml/yaml-getting-started/ for more information.
# Please review and update values in curly braces

workflows:
  default-workflow:           # workflow ID
    name: Default Workflow    # workflow name displayed in Codemagic UI
    max_build_duration: 60    # build duration in minutes (min 1, max 120)

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      # For Application environment variables
      groups:
        - autify

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      tag_patterns:
        - pattern: '*'
          include: true

    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Analyze Flutter 
        script: |
          flutter analyze

      - name: Build iOS Simulator
        script: |
          flutter build ios --debug --no-codesign

      # 
      # Upload a new build
      #
      # Params:
      # - $AUTIFY_TOKEN ... Personal Access Token created on Autify. It is added as Secret Env Var on Bitrise.
      # - $AUTIFY_PROJECT_ID ... Project ID on Autify.
      # 
      # Output:
      # - $AUTIFY_UPLOAD_STEP_RESULT_JSON
      # 
      - name: Upload a new build
        script: |
          # Create a zip file
          cd /Users/builder/clone/build/ios/Debug-iphoneos && zip -r ./build.zip ./Runner.app

          # Upload a new build to Autify
          RESPONSE=$(\
            curl -X POST \
              "https://mobile-app.autify.com/api/v1/projects/${AUTIFY_PROJECT_ID}/builds" \
              -H "accept: application/json" \
              -H "Authorization: Bearer ${AUTIFY_TOKEN}" \
              -H "Content-Type: multipart/form-data" \
              -F "file=@/Users/builder/clone/build/ios/Debug-iphoneos/build.zip;type=application/zip" \
              -w '\n%{http_code}' -s
          )

          HTTP_STATUS=$(echo "$RESPONSE" | tail -n 1)

          BODY=$(echo "$RESPONSE" | sed '$d')

          echo "export AUTIFY_UPLOAD_STEP_RESULT_JSON=${BODY}" >> ~/.zshenv

          if [[ "${HTTP_STATUS}" != "201" ]]; then
            echo ${BODY}
            exit 1
          fi

      #
      # Run a TestPlan with the build file and log TestPlanResult URL on Autify.
      #
      #
      # Params:
      # - $AUTIFY_TEST_PLAN_ID ... Test Plan ID on Autify.
      # - $AUTIFY_PROJECT_ID   ... Project ID on Autify.
      #
      - name: Run a Test Plan
        script: |
          generate_post_data() {
            cat << EOF
          {
            "build_id": "$build_id"
          }
          EOF
          }

          build_id=$(echo $AUTIFY_UPLOAD_STEP_RESULT_JSON | jq -r .id)
          echo -e "\033[00;32m *  $build_id  \033[0m"

          RESPONSE=$(\
            curl -X POST \
                 -H "Authorization: Bearer ${AUTIFY_TOKEN}" \
                 -H "Content-Type: application/json" \
                 --data "$(generate_post_data)" \
                 "https://mobile-app.autify.com/api/v1/test_plans/${AUTIFY_TEST_PLAN_ID}/test_plan_results"
          )

          test_plan_result_id=$(echo "${response}" | jq -r .id)
          echo -e "\033[00;32m * https://mobile-app.autify.com/projects/${AUTIFY_PROJECT_ID}/results/${test_plan_result_id} \033[0m"

    artifacts:
      - build/ios/Debug-iphoneos/*.app
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
