# Check out https://docs.codemagic.io/yaml/yaml-getting-started/ for more information.
# Please review and update values in curly braces

workflows:
  main-workflow:               # workflow ID
    name: Main Workflow        # workflow name displayed in Codemagic UI
    max_build_duration: 90     # build duration in minutes (min 1, max 120)

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      tag_patterns:
        - pattern: '*'
          include: true

    scripts:
      - name: "Build simulator build for Autify"
        script: |
          flutter build ios --debug --no-codesign

    artifacts:
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
