# Check out https://docs.codemagic.io/yaml/yaml-getting-started/ for more information.
# Please review and update values in curly braces

workflows:
  default-workflow:           # workflow ID
    name: Default Workflow    # workflow name displayed in Codemagic UI
    max_build_duration: 60    # build duration in minutes (min 1, max 120)

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      # For Application environment variables
      groups:
        - autify

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      tag_patterns:
        - pattern: '*'
          include: true

    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Analyze Flutter 
        script: |
          flutter analyze

      - name: Build iOS Simulator
        script: |
          flutter build ios --debug --no-codesign

      # Required Application environment variables:
      #   AUTIFY_TOKEN: Personal Access Token
      #   AUTIFY_PROJECT_ID: Project ID
      - name: Upload a new build
        script: |
          # Create a zip file
          zip -r ./upload.zip /Users/builder/clone/build/ios/Debug-iphoneos/Runner.app

          # Upload a new build to Autify
          RESPONSE=$(\
            curl -X POST \
                 -H "accept: application/json" \
                 -H "Authorization: Bearer ${AUTIFY_TOKEN}" \
                 -H "Content-Type: multipart/form-data" \
                 -F "file=@./upload.zip;type=application/zip" \
                 -w '\n%{http_code}' -s \
                 "https://mobile-app.autify.com/api/v1/projects/${AUTIFY_PROJECT_ID}/builds"
          )

          HTTP_STATUS=$(echo "$RESPONSE" | tail -n 1)

          BODY=$(echo "$RESPONSE" | sed '$d')

          if [[ "${HTTP_STATUS}" != "201" ]]; then
            echo ${BODY}
            exit 1
          fi

    artifacts:
      - build/ios/Debug-iphoneos/*.app
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
